#307 Assign type of any to asMap and asMappedResults
headintheclouddev/typings-suitescript-2.0 pull request #308
Opened 2024-09-18 15:16 UTC by bbahrman

Assigning type of any to asMap and asMappedResults allows for them to be assigned to meaningful interfaces/types

2024-09-18 17:16 UTC, ShawnTalbert commented
I would suggest we make this a generic so the caller can directly provide a return type instead of introducing 'any'.  Thoughts?

2024-09-18 17:18 UTC, darrenhillconsulting commented
I agree @ShawnTalbert , I've been meaning to do this.  @bbahrman , let me know if you need a hand converting this to use Generics.

2024-09-19 17:53 UTC, bbahrman commented
@ShawnTalbert @darrenhillconsulting - Thanks for the suggestion to use a generic, new to me, sorry it took a bit for me to get myself understanding what you were trying to do with it. Thanks Darren for the example. I think I just copied and pasted your example in, but wanted to test it out to be sure I understood the why (I trust you, but like to learn).

Do either of you feel the need to have the generic type be a named type in some way? I don't think it does, but let me know if you want any further changes.

2024-09-19 17:56 UTC, darrenhillconsulting requested changes
Maybe remove unrelated changes?  Like the JSDoc changes?

2024-09-19 17:56 UTC, darrenhillconsulting commented on N/query.d.ts
> -     * In general, the alias is an optional property.
What were these JSDoc changes?

2024-09-19 18:08 UTC, bbahrman commented
> Maybe remove unrelated changes? Like the JSDoc changes?

@darrenhillconsulting fair point, sorry those were some errant whitespace changes. I've cleaned them up.

2024-09-19 18:17 UTC, darrenhillconsulting approved these changes
I like this change.  @ShawnTalbert ?

2024-09-26 15:47 UTC, darrenhillconsulting commented
@MrRob , what's your thoughts on this one?

2024-09-26 16:26 UTC, ShawnTalbert commented
Ideally, the user would see the output as of type `T[]`, having it be `LowercaseKeys<T>[]` or even more confusing, _nested_ `LowercaseKeys<LowercaseKeys<T>>[]` isn't a great user experience. Can we do better before we unleash it on the world?

![image](https://github.com/user-attachments/assets/583c7229-f908-428d-bcdf-9aba42c47242)

2024-10-22 06:23 UTC, MrRob commented
I'm still confused on how this works.  Can someone record a quick Loom demo?  Or, I've updated the example-UserEventScript.ts to have a query in it, the old ("as any") way.  Can we update that with an example in this PR?

2024-10-22 12:18 UTC, bbahrman commented
@MrRob https://www.loom.com/share/96938eb830ec4031aa9ccd28bbe020e0

I'm still trying to figure out a solution for @ShawnTalbert 's question. I tried just renaming LowerCaseKeys back to QueryResultMap. I tried a bunch of other variations but couldn't find a cleaner option that also maintained the validations. 

In the process I also added in some result validation. Queries don't return booleans which the previous type allowed, results will be string, number, or null.

2024-10-22 17:26 UTC, ShawnTalbert commented
Try something like
```typescript
export type QueryMapResult<T> = {
    [K in keyof T as Lowercase<K & string>]: T[K]
};
```
which should provide an experience something like this in the IDE:
![image](https://github.com/user-attachments/assets/15485e7c-8919-45eb-b608-91ef56e0e384)

Note that the CTRL+Q popup shows the _uppercase_ foo from the original type; as long as we're ok with that, this type enforces the lowercase keys in a single (not nested) return type for `asMappedResults()`.  

I wonder though, are the lowercase shenanigans worth it? Instead of type magic to convert the keys to lowercase, why not force the user supplied type to actually have lowercase keys? I mean, why encourage or support a user passing a type with uppercase keys as I show in that screenshot at all? Instead, force them to provide a type that contains lowercase keys only?

2024-10-22 17:37 UTC, ShawnTalbert commented
Actually, that constraint seems to hold already - I should have just had my vanilla defined type - not involving `QueryMapResult`explicitly.
For example this seems to satisfy the compiler:
```typescript
    let r: ResultSet = {} as ResultSet
    interface F { foo:number, bar:string, baz:string }
    const mapped = r.asMappedResults<F>()
    if (mapped[0].foo === 2)
```
but trying to sneak in an uppercase `Bar` will be rejected:
![image](https://github.com/user-attachments/assets/dbbf7c98-e006-4561-9586-d6a09eb48f3b)

So maybe the modification I suggested above for `QueryMapResult` is adequate?

2024-10-22 17:44 UTC, ShawnTalbert commented
> @MrRob https://www.loom.com/share/96938eb830ec4031aa9ccd28bbe020e0
> 
> I'm still trying to figure out a solution for @ShawnTalbert 's question. I tried just renaming LowerCaseKeys back to QueryResultMap. I tried a bunch of other variations but couldn't find a cleaner option that also maintained the validations.
> 
> In the process I also added in some result validation. Queries don't return booleans which the previous type allowed, results will be string, number, or null.

@bbahrman , the small change from my replies about is to be sure we type each key to match the type in the user-provided generic  - otherwise **every** key had type `string | number | null` rather than having the types of individual keys passed as `T`. From my examples above, the keys `foo, bar, baz` have distinct concrete types of `number, string,string` respectively - that should hopefully be reflected in the output after mapping, no?

2026-07-08 09:47 UTC, MrRob commented
Thanks Ben and @ShawnTalbert and @darrenhillconsulting for the thoughtful review iterations.

After sitting with this for a while, I'm going to close it. The discussion surfaced enough complexity (lowercase key mapping, preserving per-key value types, keeping the existing QueryResultMap export and zero-argument calls backwards compatible) that I'm not convinced the added type surface is worth it versus the current approach, where callers cast mapped results to their own interfaces. Nobody has pushed on this in some time, so I'd rather keep the module simple.

If the need becomes pressing again, happy to revisit with a fresh design on issue #307 — the ideas explored here (especially Shawn's Lowercase<K & string> mapping with T[K] values) would be the right starting point.

2026-07-08 09:47 UTC, closed without merging